import numpy as np
a=np.array([2,4,6,8,10])

print("~~BASIC MATHEMATICAL OPERATIONS~~")
print("Orginal array:",a)
print("Add 5:",a+5)
print("Squared array:",a**2)
print("Square root:", np.sqrt(a))
print("Natural log:", np.log(a))

print("\n~~LINEAR ALGEBRA~~")
x=np.array([[1,3],[5,7]])
y=np.array([[10,11],[15,16]])
print("Matrix X:",x)
print("Matrix Y:",y)
print("X+Y:",x+y)
print("X-Y:",x-y)
print("X*Y",x*y)
y_inv=np.linalg.inv(y)
div=np.dot(x,y_inv)
print("x/y:",div)
print("Matrix multiplication:",np.dot(x,y))

print("\n~~RANDOM NUMBER GENERATION~~")
rand_arr=np.random.randint(1,21,size=5)
rand2=np.random.randint(1,21,size=(2,2))
rand3=np.random.rand(2,3)
print("Random integers (1-20):",rand_arr)
print("Random 2x2 array (1-20):",rand2)
print("Random float array:",rand3)

print("\n~~STATISTICAL FUNCTIONS~~")
data=np.array([10,20,30])
print("Data:",data)
print("Mean:",np.mean(data))
print("Median:", np.median(data))
print("Max:", np.max(data))
print("Min:", np.min(data))
print("Standard Deviation:", np.std(data))
